### ISSUE TITLE
ISSUE#5 Προσθήκη τραγουδιών στα αγαπημένα του χρήστη

### ISSUE THREAD

**Issue by AlexanderMnxs** [ApolloTkog/Sporify#13]
Ο χρήστης να μπορεί να προσθέσει ένα τραγούδι στα αγαπημένα του το οποίο θα αποθηκέυεται στον λογαριασμό του.

**Comment by AceTsak** [comment]
Πρόσθεση του κουμπιού Favourite στην κλάση TrackDetails ώστε ο χρήστης να μπορεί να βάζει τραγούδια ως αγαπημένα.

**Comment by delefjt** [comment]
Ολοκληρώθηκε και προστέθηκε

**Comment by AceTsak** [comment]
private void addFavorite(){
        // listener when add favorite is tapped
        addFavorite.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Observer<String> observer1 = new Observer<String>() {
                    @Override
                    public void onChanged(String response) {
                        if(response == null)
                            return;

                        Toast.makeText(getApplicationContext(), response, Toast.LENGTH_SHORT).show();

                        favoriteTrackViewModel.getFavoriteTracksResponse().removeObservers(TrackDetails.this);
                    }
                };

                favoriteTrackViewModel.init(searchable.getMbid(), token, trackInfo);

                favoriteTrackViewModel.getFavoriteTracksResponse().observe(TrackDetails.this, observer1);
            }
        });
    }

**Comment by AceTsak** [comment]
`                    Toast.makeText(getApplicationContext(), response, Toast.LENGTH_SHORT).show();

                    favoriteTrackViewModel.getFavoriteTracksResponse().removeObservers(TrackDetails.this);
                }
            };

            favoriteTrackViewModel.init(searchable.getMbid(), token, trackInfo);

            favoriteTrackViewModel.getFavoriteTracksResponse().observe(TrackDetails.this, observer1);
        }
    });
}`
