### ISSUE TITLE
ISSUE#7 Προσθήκη καλλιτεχνών στα αγαπημένα του χρήστη

### ISSUE THREAD

**Issue by AlexanderMnxs** [ApolloTkog/Sporify#15]
Ο χρήστης μπορεί να προσθέτει έναν καλλιτέχνη στα αγαπημένα του και να αποθηκεύεται στη συγκεκριμένη λίστα.

**Comment by delefjt** [comment]
Ολοκληρώθηκε και προστέθηκε
